gazer/models.py
#from main import db
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
import json

from sqlalchemy import create_engine, desc
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, scoped_session

Base = declarative_base()

engine = create_engine('sqlite:///postdata.db', connect_args={'check_same_thread': False})


class Posts(Base):
    __tablename__ = 'posts'

    filename = Column(String, primary_key=True)
    id = Column(Integer)
    booru = Column(String)
    source = Column(String)
    score = Column(Integer)
    tags = Column(String)
    dd_tags = Column(String)
    rating = Column(String)
    created_at = Column(Integer)
    status = Column(String)
    creator_id = Column(Integer)
    change = Column(Integer)
    views = Column(Integer, default=0)

    @staticmethod
    def from_tuple(data):
        '''
        Enables initializing from a tuple to support raw
        queries.
        '''
        return Posts(
            filename=data[0],
            id=data[1],
            booru=data[2],
            source=data[3],
            score=data[4],
            tags=data[5],
            rating=data[6],
            created_at=data[7],
            status=data[8],
            creator_id=data[9],
            change=data[10],
            views=data[11],
        )

    def get_filepath(self, filename):
        '''
        Return full static filepath for filename using
        our two depth hash prefix scheme.
        '''
        if filename:
            return 'static/dump/{}/{}/{}'.format(filename[:2], filename[2:4], filename)
        else:
            return None

    def as_dict(self):
        '''
        Returns posts instance as a json object
        '''
        data = {'filename':self.filename, 'id':self.id,
            'booru':self.booru,
            'source':self.source,
            'score':self.score,
            'tags':self.tags.split('|'),
            'dd_tags': self.dd_tags.split('|') if self.dd_tags else None,
            'rating':self.rating, 'created_at':self.created_at,
            'status':self.status, 'creator_id':self.creator_id,
            'change':self.change,
            'file':self.get_filepath(self.filename),
            'views':self.views,
            }

        return data


class Tag(Base):
    __tablename__ = 'tag'

    tag = Column(String, primary_key=True)
    count = Column(Integer)
    type = Column(String)
    ambiguous = Column(Integer)
    source = Column(String)
    views = Column(Integer, default=0)

    def as_dict(self):
        '''
        Returns tag instance as a json object
        '''
        data = {'tag':self.tag, 'count':self.count, 'type':self.type, 'ambiguous':self.ambiguous,
            'source':self.source, 'views':self.views
            }

        return data

    @classmethod
    def serialize_tags(cls, tags=None, increment_views=False):
        serialized_tags = {'artist':[], 'character':[], 'copyright':[], 'tag':[]}
        tags = cls.get_tags(tags, increment_views)

        for tag in tags:
            if tag.get('type') == 'artist':
                serialized_tags['artist'].append(tag)
            elif tag.get('type') == 'character':
                serialized_tags['character'].append(tag)
            elif tag.get('type') == 'copyright':
                serialized_tags['copyright'].append(tag)
            else:
                serialized_tags['tag'].append(tag)

        return serialized_tags

    @classmethod
    def get_tags(cls, tags=None, increment_views=False):
        '''
        Grab tag data from the local db
        '''
        local_tags = []
        for tag in tags:
            local_tag = session.query(cls).filter(cls.tag == tag).first()
            session.flush()
            if local_tag:
                # increment views for each local tag we grabbed
                if increment_views:
                    local_tag.views += 1
                local_tags.append(local_tag.as_dict())
            # tag isn't in db happens for dd derived tags
            else:
                local_tags.append({'tag':tag})
        session.commit()

        return local_tags


#Base.metadata.create_all(engine)

Session = sessionmaker(bind = engine)
session = scoped_session(Session)

gazer/templates/base.html
<html>
    <head>
      <link rel="apple-touch-icon" sizes="180x180" href="/static/apple-touch-icon.png">
      <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon-16x16.png">
      <link rel="manifest" href="/site.webmanifest">
      <link rel="stylesheet" href='/static/css/base.css'/>

    <title>Gazer</title>
    </head>
    <body>
      <a href="/"><h1><img src="/static/android-chrome-512x512.png" type="image/png" width=40 height=40></a> Gazer </h1>

      <form class="search-row" action="/posts">
        <input type="text" name="tags" value="{{tags}}" list="datalist" 
          oninput="tagComplete(this.value).then( function(result) {
            document.getElementById('datalist').innerHTML = result; 
          })">

        <datalist id="datalist">
        </datalist>

        <label for="limit">Service:</label>
        <select name="service" id="service-select">
          <option value="archive" {{"selected" if service == "archive"}}>Archive</option>
          <option value="gelbooru" {{"selected" if service == "gelbooru"}}>Gelbooru</option>
          <option value="yandere" {{"selected" if service == "yandere"}}>Yandere</option>
          <option value="konachan" {{"selected" if service == "konachan"}}>Konachan</option>
          <option value="lolibooru" {{"selected" if service == "lolibooru"}}>Lolibooru</option>
          <option value="safebooru" {{"selected" if service == "safebooru"}}>Safebooru</option>
        </select>

        {% if service == "archive" %}
        <input type="checkbox" id="dd_enabled" name="dd_enabled" value="enabled" {{"checked" if dd_enabled}}>
        <label for="dd_enabled">DD</label>
        <label for="limit">Sort:</label>
        <select name="sort" id="sort-select">
          <option value="created-desc" {{"selected" if sort == "created-desc"}}>Created - desc</option>
          <option value="created-asc" {{"selected" if sort == "created-asc"}}>Created - asc</option>
          <option value="score-desc" {{"selected" if sort == "score-desc"}}>Score - desc</option>
          <option value="score-asc" {{"selected" if sort == "score-asc"}}>Score - asc</option>
          <option value="views-desc" {{"selected" if sort == "views-desc"}}>Views - desc</option>
          <option value="views-asc" {{"selected" if sort == "views-asc"}}>Views - asc</option>
        </select>
        {% endif %}

        <label for="limit">Limit:</label>
        <select name="limit" id="limit">
          <option value=10 {% if limit == 10 %}selected{% endif %}>10</option>
          <option value=25 {% if limit == 25 %}selected{% endif %}>25</option>
          <option value=50 {% if limit == 50 %}selected{% endif %}>50</option>
          <option value=100 {% if limit == 100 %}selected{% endif %}>100</option>
          <option value=200 {% if limit == 200 %}selected{% endif %}>200</option>
        </select>

        <label for="thumb_size">Thumb Size:</label>
        <select name="thumb_size" id="thumb-size-select" onchange="resizeThumbs()">
          <option value=100 {% if thumb_size == 100 %}selected{% endif %}>100</option>
          <option value=200 {% if thumb_size == 200 %}selected{% endif %}>200</option>
          <option value=300 {% if thumb_size == 300 %}selected{% endif %}>300</option>
          <option value=400 {% if thumb_size == 400 %}selected{% endif %}>400</option>
          <option value=500 {% if thumb_size == 500 %}selected{% endif %}>500</option>
        </select>

        <input type="submit" value="search">
      </form>

      {% block content %}
      {% endblock %}

    </body>
</html>

gazer/templates/index.html
{% extends "base.html" %}
{% block content %}
<a href="/posts">Main</a><p>
<a href="/scraper">Scraper</a><p>
<a href="/tags">Tag Archive Stats</a><p>
<a href="/poststats">Post Archive Stats</a>
{% endblock content %}

gazer/templates/post.html
{% extends "base.html" %}
{% block content %}
<script src="/static/js/posts_utility.js"></script>

{% if not archived %}
<form action="" class="search-row">
  <input type="hidden" name="service" value="{{service}}">
  <input type="hidden" name="tags" value="{{tags}}">
  <input type="hidden" name="limit" value="{{limit}}">
  <input type="hidden" name="sort" value="{{sort}}">
  <input type="hidden" name="thumb_size" value="{{thumb_size}}">
  <input type="hidden" name="dd_enabled" value="{{dd_enabled}}">
  <input type="hidden" name="archive" value="true">
  <input type="submit" value="Archive">
</form>
{% endif %}

<div class="post-main">
  <tags>
    <h4>Artist</h4>
    <ul>
    {% for tag in post_tags.artist %}
      <li><a href="/posts?tags={{tag.tag}}&service={{service}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}">{{tag.tag}}</a></li>
    {% endfor %}
    </ul>
    <h4>Character</h4>
    <ul>
    {% for tag in post_tags.character %}
      <li><a href="/posts?tags={{tag.tag}}&service={{service}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}">{{tag.tag}}</a></li>
    {% endfor %}
    </ul>
    <h4>Copyright</h4>
    <ul>
    {% for tag in post_tags.copyright %}
      <li><a href="/posts?tags={{tag.tag}}&service={{service}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}">{{tag.tag}}</a></li>
    {% endfor %}
    </ul>
    <h4>Tags</h4>
    <ul>
    {% for tag in post_tags.tag %}
      <li><a href="/posts?tags={{tag.tag}}&service={{service}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}">{{tag.tag}}</a></li>
    {% endfor %}
    </ul>
    {% if service == "archive" %}
    <p>
      <details>
      <summary>DD Tags</summary>
      <ul>
      {% for tag in dd_tags.tag %}
        <li><a href="/posts?tags={{tag.tag}}&service={{service}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}">{{tag.tag}}</a></li>
      {% endfor %}
      </ul>
      </details>
    {% endif %}
    </tags>

    <post>
    {% if post.video %}
      <video controls width=90%>
        <source src="../{{post.file}}" type="video/webm">
      </video>
    {% else %}
      <img src="../{{post.file}}" width=90%>
    {% endif %}
    <p>
    <details>
    <summary>details</summary>
      id: {{post.id}}<p>
      {% if archived %}
        views: {{post.views}}<p>
        booru: {{post.booru}}<p>
      {% endif %}
      source: {{post.source}}<p>
      rating: {{post.rating}}<p>
      score: {{post.score}}<p>
      created: {{post.created_at}}
      </details>
    </post>

</div>
{% endblock %}




    </body>
</html>

gazer/templates/posts.html
{% extends "base.html" %}
{% block content %}
<script src="/static/js/posts_utility.js"></script>


<div class="posts-container">
  {% if page >= 1 %}
  <a href="?page={{page - 1}}&tags={{tags}}&service={{service}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}" class="prev-button">
    <div class="navigation-button">
    </div>
  </a>
  {% endif %}

  <div class="post-grid">
    {% for post in posts: %}
      {% if post.thumbnail is defined %}
        <a href="post/{{post.id}}?service={{service}}&tags={{tags}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}">
          <img src="{{post.thumbnail}}", class="post" width={{thumb_size}}>
        </a>
      {% elif post.video is true %}
        <a href="post/{{post.id}}?service={{service}}&tags={{tags}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}" color="red">
          <video width={{thumb_size}} style='border: 3px solid #003399;'>
            <source src="../{{post.file}}" type="video/webm">
          </video>
        </a>
      {% else %}
        <a href="post/{{post.id}}?service={{service}}&tags={{tags}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}">
          <img src="{{post.file}}", class="post" width={{thumb_size}}>
        </a>
      {% endif %}
    {% endfor %}
  </div>

  <a href="?page={{page + 1}}&tags={{tags}}&service={{service}}&limit={{limit}}&sort={{sort}}&thumb_size={{thumb_size}}&dd_enabled={{dd_enabled}}" class="next-button">
    <div class="navigation-button">
    </div>
  </a>

</div>

{% endblock content %}

gazer/templates/poststats.html
{% extends "base.html" %}
{% block content %}
      <ul>
        {% for post in posts: %}
          <li><a href="/post/{{post.id}}">{{post.filename}}</a> - views: {{post.views}}</li>
        {% endfor %}
      </ul>
{% endblock content %}

gazer/templates/scraper.html
{% extends "base.html" %}
{% block content %}
<h2>Scraper</h2>
<b>Active:</b> {{status.active}}<p>
<b>Currently Downloading:</b> {{status.current_tags}}<p>
<b>Images Downloaded:</b> {{status.images_downloaded}}<p>
<b>Complete:</b> {{status.finished}}<p>

<h2>Tag List</h2>
<form action="/scraper" method="post">
  <button type="submit">Restart</button>
</form>
<ul>
{% for set in tag_set: %}
  <li>{{set.name}} - {{set.tags}}</li>
{% endfor %}
</ul>
<p>
{% endblock content %}

gazer/templates/tags.html
{% extends "base.html" %}
{% block content %}
<h2>Local Tags</h2>
<ul>
{% for tag in tags: %}
  <li><a href="/tag/{{tag.tag}}">{{tag.tag}}</a> - views: {{tag.views}}</li>
{% endfor %}
</ul>
{% endblock content %}